/*
** EPITECH PROJECT, 2024
** my_rpg
** File description:
** check_input
*/

#include "my_rpg.h"

const keyy_t list_key[100] = {
    {sfKeyA, "A"},
    {sfKeyB, "B"},
    {sfKeyC, "C"},
    {sfKeyD, "D"},
    {sfKeyE, "E"},
    {sfKeyF, "F"},
    {sfKeyG, "G"},
    {sfKeyH, "H"},
    {sfKeyI, "I"},
    {sfKeyJ, "J"},
    {sfKeyK, "K"},
    {sfKeyL, "L"},
    {sfKeyM, "M"},
    {sfKeyN, "N"},
    {sfKeyO, "O"},
    {sfKeyP, "P"},
    {sfKeyQ, "Q"},
    {sfKeyR, "R"},
    {sfKeyS, "S"},
    {sfKeyT, "T"},
    {sfKeyU, "U"},
    {sfKeyV, "V"},
    {sfKeyW, "W"},
    {sfKeyX, "X"},
    {sfKeyY, "Y"},
    {sfKeyZ, "Z"},
    {sfKeyNum0, "0"},
    {sfKeyNum1, "1"},
    {sfKeyNum2, "2"},
    {sfKeyNum3, "3"},
    {sfKeyNum4, "4"},
    {sfKeyNum5, "5"},
    {sfKeyNum6, "6"},
    {sfKeyNum7, "7"},
    {sfKeyNum8, "8"},
    {sfKeyNum9, "9"},
    {sfKeyLControl, "LEFT CONTROL"},
    {sfKeyLShift, "LEFT SHIFT"},
    {sfKeyLAlt, "LEFT ALT"},
    {sfKeyLSystem, "WINDOWS"},
    {sfKeyRControl, "RIGHT CONTROL"},
    {sfKeyRShift, "RIGHT SHIFT"},
    {sfKeyRAlt, "RIGHT ALT"},
    {sfKeyRSystem, "ALT GR"},
    {sfKeyMenu, "MENU"},
    {sfKeyLBracket, "{"},
    {sfKeyRBracket, "}"},
    {sfKeySemicolon, ";"},
    {sfKeyComma, ", "},
    {sfKeyPeriod, "."},
    {sfKeyQuote, "'"},
    {sfKeySlash, "/"},
    {sfKeyBackslash, "\\"},
    {sfKeyTilde, "~"},
    {sfKeyEqual, " = "},
    {sfKeySpace, "SPACE"},
    {sfKeyEnter, "ENTER"},
    {sfKeyBackspace, "BACKSPACE"},
    {sfKeyTab, "TAB"},
    {sfKeyPageUp, "PAGE UP"},
    {sfKeyPageDown, "PAGE DOWN"},
    {sfKeyEnd, "END"},
    {sfKeyHome, "HOME"},
    {sfKeyInsert, "INSERT"},
    {sfKeyDelete, "SUPPR"},
    {sfKeyAdd, "+"},
    {sfKeySubtract, "-"},
    {sfKeyMultiply, "*"},
    {sfKeyDivide, "/"},
    {sfKeyLeft, "LEFT ARROW"},
    {sfKeyRight, "RIGHT ARROW"},
    {sfKeyUp, "UP ARROW"},
    {sfKeyDown, "DOWN ARROW"},
    {sfKeyNumpad0, "NUMPAD 0"},
    {sfKeyNumpad1, "NUMPAD 1"},
    {sfKeyNumpad2, "NUMPAD 2"},
    {sfKeyNumpad3, "NUMPAD 3"},
    {sfKeyNumpad4, "NUMPAD 4"},
    {sfKeyNumpad5, "NUMPAD 5"},
    {sfKeyNumpad6, "NUMPAD 6"},
    {sfKeyNumpad7, "NUMPAD 7"},
    {sfKeyNumpad8, "NUMPAD 8"},
    {sfKeyNumpad9, "NUMPAD 9"},
    {sfKeyF1, "F1"},
    {sfKeyF2, "F2"},
    {sfKeyF3, "F3"},
    {sfKeyF4, "F4"},
    {sfKeyF5, "F5"},
    {sfKeyF6, "F6"},
    {sfKeyF7, "F7"},
    {sfKeyF8, "F8"},
    {sfKeyF9, "F9"},
    {sfKeyF10, "F10"},
    {sfKeyF11, "F11"},
    {sfKeyF12, "F12"},
    {sfKeyF13, "F13"},
    {sfKeyF14, "F14"},
    {sfKeyF15, "F15"},
    {sfKeyPause, "PAUSE"},
    {-1, NULL}
};
